Specification Requirement -  Markdown
nFocusTesting/real-world-testing pull request #1
Opened 2024-02-13 17:33 UTC by Nethmaw

Specification requirement document based on the conduit website written in a markdown file

2024-02-13 18:13 UTC, dannycrone commented on specificationRequirements
It looks like this file does not have extension - I would expect it to have been called requirements-specification.md

2024-02-13 18:14 UTC, dannycrone commented on specificationRequirements
Also, I was expecting this to be in a directory of its own - e.g. docs

2024-02-13 18:18 UTC, dannycrone requested changes
I have left a few comments on here which need to be resolved before I can approve them

2024-02-14 10:22 UTC, Nethmaw commented on specificationRequirements
The naming has been changed

2024-02-14 10:22 UTC, Nethmaw commented on specificationRequirements
DOCS folder created

2024-02-14 10:29 UTC, Nethmaw commented on prisma/db.sqlite
This file will be deleted

2024-02-14 10:47 UTC, dannycrone commented on prisma/db.sqlite
> This file will be deleted

I don't think you want to delete this file, I think you just want to undo the changes to it

2024-02-14 10:48 UTC, dannycrone commented on specificationRequirements
Cool with that

2024-02-14 10:50 UTC, dannycrone commented on DOCS/specificationRequirements.txt
Why do you need this file

2024-02-14 20:20 UTC, dannycrone commented on prisma/db.sqlite
I guess it is fine

2024-02-14 20:26 UTC, dannycrone commented on DOCS/specificationRequirements.txt
I've fixed this up with commit 9a0855fbf147d69e7b8cefae6fdbe6bc3b0e4b20

2024-02-14 20:27 UTC, dannycrone commented on DOCS/requirements-specification.md
I resolved this with 0f908d31c77eb6ea591a0ee8080549349f5cdf39 followed by ba1f9082a57aaeda0fd42d8d2aacd8daeae82777

2024-02-14 20:29 UTC, dannycrone approved these changes

2024-02-14 20:29 UTC, merged